// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jisdystalysfvpzpjntd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppc2R5c3RhbHlzZnZwenBqbnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NzQyMjksImV4cCI6MjA4NTA1MDIyOX0.oWy9UszRs2dT2_D_B-huzMQ0OWzrDYd1slkPDtjvtT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);